# Site wide configuration

title:            Developer's Diary.
locale:           en_US
#url:              http://minhaj.io
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Minhaj Mehmood
  avatar: avatar.jpg
  bio: "Backend Grails Developer"
  email: minhaj.kk+blog@gmail.com
  disqus-shortname: ghpages
  twitter: minhajkk
  facebook: #username
  google:
    plus: MinhajMehmood
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: minhajkk
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: minhajkk
  instagram: #username
  lastfm: #username
  tumblr: minhaj
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
